server:
 port: 9010 
spring:
 application:
  name: service-account
 jpa:
  database: postgresql
  show-sql: true
  hibernate:
   ddl-auto: create
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/account
  username: postgres
  password: postgres

eureka:
 client:
  service-url:
   defaultZone: http://localhost:9090/eureka

customer:
 personal:
  url: http://localhost:9001/customerpersonal/
 business:
  url: http://localhost:9001/customerbusiness/

card:
 validate:
  url: http://localhost:9040/card/document/