server:
 port: 9020
spring: 
 application:
  name: service-credit
 jpa:
  database: postgresql
  show-sql: false
  hibernate:
   ddl-auto: create
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/creditsdb
  username: postgres
  password: postgres

eureka:
 client:
  service-url:
   defaultZone: http://localhost:9090/eureka
